name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install uv
          uv venv
          make install
      - name: Run linter and pytest
        run: |
          make check
          - name: Run test coverage
          run: |
            make test-coverage
        - name: SonarQubeScan
          uses: SonarSource/sonarqube-scan-action@v6
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          with:
            args: >
              -Dsonar.projectKey=volhapunko_python-project-83
              -Dsonar.organization=volhapunko
              -Dsonar.python.coverage.reportPaths=coverage.xml
